#!/bin/bash

echoerr() { echo "$@" 1>&2; }

MODE=$([ -d /sys/firmware/efi ] && echo -n UEFI || echo -n BIOS)
if [ "x$MODE" == "xBIOS" ]; then
    echoerr "This script is for UEFI boot only."
    exit 9
fi

BOOTCURRENT=`efibootmgr -v | grep 'BootCurrent' | awk '{print $2}'`
if [ -z "$BOOTCURRENT" ]; then
    echoerr "Unable to determine current boot entry number"
    exit 1
fi
EFIENTRY=`efibootmgr -v | grep Boot${BOOTCURRENT} | egrep -o '[a-zA-Z0-9.,()/\-]*' | grep .efi`
if [ -z "$EFIENTRY" ]; then
    echoerr "Unable to determine current boot entry data"
    exit 2
fi
echoerr "EFIENTRY=$EFIENTRY"
UUID=`echo $EFIENTRY | awk -F, '{print $3}'`
if [ -z "$UUID" ]; then
    echoerr "Unable to determine current boot entry UUID"
    exit 3
fi
EFIFILE=`echo $EFIENTRY | awk -F'/File' '{print $2}' | egrep -o '[a-zA-Z0-9.,/\-]*' | head -n 1 | sed 's/\\\\/\\//g'`
if [ -z "$EFIFILE" ]; then
    echoerr "Unable to determine current boot entry filename"
    exit 3
fi
echoerr "UUID=$UUID, EFIFILE=$EFIFILE"
# searches all disks. uses sfdisk to dump uuids on each disk. greps for the $UUID. if there are multiple matches
# (should not occur), select the first and only
EFIDISK=`for disk in /dev/sd?; do sfdisk -d $disk | grep -i uuid=$UUID | awk '{print $1}'; done | head -n 1`
if [ -z "$EFIDISK" ]; then
    echoerr "Unable to determine current boot entry UUID disk (is the partition still present?)"
    exit 4
fi
echoerr "EFIDISK=$EFIDISK"
MOUNTPOINT=`mount | grep $EFIDISK | awk '{print $3}'`
if [ -z "$MOUNTPOINT" ]; then
    echoerr "Unable to determine current boot entry UUID disk (is the disk present?)"
    exit 5
fi
echoerr "MOUNTPOINT=$MOUNTPOINT"
LOADERFILE="${MOUNTPOINT}$EFIFILE"
if [ -z "$LOADERFILE" ]; then
    echoerr "Unable to determine current boot entry filename."
    exit 5
fi
if [ ! -f "$LOADERFILE" ]; then
    echoerr "Boot entry file not found. Is the boot file for EFI boot still present?"
    exit 5
fi
echoerr "Hashing $LOADERFILE"
pcrsum -e -l $LOADERFILE
