Document: tpm-luks
Title: Debian tpm-luks Manual
Author: <insert document author here>
Abstract: This manual describes what tpm-luks is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tpm-luks/tpm-luks.sgml.gz

Format: postscript
Files: /usr/share/doc/tpm-luks/tpm-luks.ps.gz

Format: text
Files: /usr/share/doc/tpm-luks/tpm-luks.text.gz

Format: HTML
Index: /usr/share/doc/tpm-luks/html/index.html
Files: /usr/share/doc/tpm-luks/html/*.html
